name: Deploy to Production

on: workflow_dispatch

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build and Deploy Prod
        id: builddeployprod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          api_location: 'build/server'
          output_location: 'build'
